### ISSUE TITLE
Error: Unable to access jarfile bundlesigner-0.1.0.jar

### ISSUE THREAD

**Issue by habibi-dev** [cafebazaar/bundle-signer#1]
سلام
من موقع خروجی با خطا زیر روبرو میشم 
Error: Unable to access jarfile bundlesigner-0.1.0.jar
این فایل رو ما باید خودمون داشته باشیم ؟ 
bundlesigner-0.1.0.jar

**Comment by mahboobehad** [comment]
سلام
باندل ساینر رو می‌تونید کامپایل کنید یا اینکه از لینک زیر دانلود کنید
https://github.com/cafebazaar/bundle-signer/releases

**Comment by habibi-dev** [comment]
ممنون حل شد

مشکل دیگه ایکه دارم برای ساخت فایل امضا هست 
`Failed to load signer "signer #1"
java.security.spec.InvalidKeySpecException: Failed to load PKCS #8 encoded private key`

با این دستور هم کلیدم رو میسازم 
`ssh-keygen -t dsa -b 1024 -m PKCS8 -f pubkey.pem`

نمیدونم کجا رو اشتباه میکنم

**Comment by mahboobehad** [comment]
نیازی نیست کلید جدید بسازید، کلیدی که قبلا برای ساین برنامه استفاده می‌کردید رو به باندل‌ساینر ورودی بدید تا ساین بسته‌های جدیدی که با باندل ایجاد می‌شه  با نسخه‌های قبلی یکسان باشه. 
.اگر باز هم به مشکل خوردید لطفا دستور کاملی که اجرا می‌کنید رو بنویسید

**Comment by habibi-dev** [comment]
`java -jar bundlesigner-0.1.0.jar genbin  -v --bundle app-release.aab --bin /home/habibi/Desktop/ --v2-signing-enabled true --v3-signing-enabled false --key '/home/habibi/Projects/Task-management/key/key.jks' `

من مقدار --cert رو نمیدونم چی باید بدم

**Comment by srmarjani** [comment]
شما دارین از Keystore استفاده می کنیم برای این کار از فلگ --ks استفاده کنید لازم نیست key و cert رو بدید

`java -jar bundlesigner-0.1.0.jar genbin -v --bundle app-release.aab --bin /home/habibi/Desktop/ --v2-signing-enabled true --v3-signing-enabled false --ks '/home/habibi/Projects/Task-management/key/key.jks'`

**Comment by habibi-dev** [comment]
ممنون رفع شد کامللل
