### ISSUE TITLE
support .keystore extension

### ISSUE THREAD

**Issue by aminsaedi** [cafebazaar/bundle-signer#10]
I'm new to react native CLI and building app with android studio.
`keytool -genkeypair -v -storetype PKCS12 -keystore my-upload-key.keystore -alias my-key-alias -keyalg RSA -keysize 2048 -validity 10000`
I ran this command and it give me a .keystore file.
How can I use this file with bundler signer?

**Comment by mahboobehad** [comment]
Hello 
You can provide your key using java key store flags. See [this section](https://github.com/cafebazaar/bundle-signer#java-keystore-flags.

**Comment by sajaddp** [comment]
@aminsaedi 
سلام
این مشکل رو تونستید رفع کنید؟
اگر موفق شدید کامند را به چه صورتی نوشتید؟

**Comment by aminsaedi** [comment]
سلام، فایل .keystore با فایل .jks تفاوتی ندارن. میتونین از همون استفاده کنین
