### ISSUE TITLE
No bin file generated after process 

### ISSUE THREAD

**Issue by AlirezaHadjar** [cafebazaar/bundle-signer#11]
After running " java -jar bundlesigner-0.1.5.jar genbin  -v --bundle app-release.aab --bin .  --v2-signing-enabled true --v3-signing-enabled false  --ks key.keystore" it requires password. and after about 5 seconds the process finishes but no file generated.
os: Mac os Big Sur v 11.4

**Comment by mahboobehad** [comment]
Please send output of the following command. 
`java -XX:+PrintCommandLineFlags -version`

**Comment by AlirezaHadjar** [comment]
> java -XX:+PrintCommandLineFlags -version

-XX:InitialHeapSize=134217728 -XX:MaxHeapSize=2147483648 -XX:+PrintCommandLineFlags -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:+UseParallelGC 
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)

**Comment by mahboobehad** [comment]
There's an issue with older versions of Java, Please retry with Java 11.

**Comment by AlirezaHadjar** [comment]
> There's an issue with older versions of Java, Please retry with Java 11.

thank you my problem solved
