### ISSUE TITLE
hidden break in command

### ISSUE THREAD

**Issue by mdehghani65** [cafebazaar/bundle-signer#13]
there is a hidden break in the command mentioned in the document when you want to copy/paste it: 

>java -jar bundlesigner-0.1.6.jar genbin  -v --bundle app.aab --bin /home/bin_files/  --v2-signing-enabled true 
--v3-signing-enabled false  --ks key.jks 

splits into : 
>java -jar bundlesigner-0.1.6.jar genbin  -v --bundle app.aab --bin /home/bin_files/  --v2-signing-enabled true

and : 

>--v3-signing-enabled false  --ks key.jks 

working example: 
>java -jar bundlesigner-0.1.6.jar genbin  -v --bundle '/Users/mdbaniani/Downloads/bazaarbundlesigning/app.aab' --bin '/Users/mdbaniani/Downloads/bazaarbundlesigning/'  --v2-signing-enabled true --v3-signing-enabled false  --ks '/Users/mdbaniani/Downloads/bazaarbundlesigning/key.jks'

**Comment by mahboobehad** [comment]
Thanks for the report. It's fixed now.
