### ISSUE TITLE
Windows error "Input bundle file does not exist" in recent versions of bundle-signer

### ISSUE THREAD

**Issue by HessiPard** [cafebazaar/bundle-signer#15]
Hi, in recent versions of bundle-signer 0.1.5 and 0.1.6, bundle-signer can't read the input bundle but in past versions it was ok.

<img width="602" alt="bundle-signer" src="https://user-images.githubusercontent.com/23122664/129487161-ad3cb9c5-1da3-4498-8e10-23d7b50cb4d1.PNG">

**Comment by srmarjani** [comment]
سلام. اگه امکانش هست از ساختار فولدری که دارین دستور رو اجرا می کنین یه تصویر بزارین . ممنون

**Comment by srmarjani** [comment]
سلام. ممنون از اینکه این باگ رو گزارش کردید.
فعلا برای این که مشکل حل بشه قبل از اجرای دستور در مسیر حتما فولدر bin_files رو ایجاد کنید.

**Comment by HessiPard** [comment]
I fixed issue by doing belows and don't know exactly which one fixed my problem.
Anyway these could be mentioned in doc:

1- Setting output to "."
2- Update my JRE to 8.301 and my JDK to 16.0.2
3- Increased my heap size in windows by -Xmx3072m (go to java control panel and in java tab select view and manage java runtime versions)

Thanks.

**Comment by mhkarami** [comment]
I put the files `bundlesigner-0.1.6.jar` and `app-release.aab` and `MyKeyStore.jks` in a folder and created directories `/home` and `/home/bin_files` and `/bin_files` in that folder .but still i face with this error:  `Input bundle file does not exist`
 `java -jar bundlesigner-0.1.6.jar genbin  -v --bundle app-release.aab --bin /home/bin_files/  --v2-signing-enabled true --v3-signing-enabled false --ks MyKeyStore.jks --ks-pass pass:XXXXXXXXXX`
