### ISSUE TITLE
33 MB aab file into 3 MB bin ?

### ISSUE THREAD

**Issue by club9822** [cafebazaar/bundle-signer#16]
یک پروژه ری اکت نتیو داریم که حجم  ورژن ای ای بی ۳۳ مگ میشه. چطور میشه که به ۳ مگ  تبدیل میشه ؟
بعد تو آپلود به "مشکلی در شناسایی بسته‌ها پیش‌ آمده است، لطفا فایل باینری را دوباره تولید و بارگذاری کنید.
  میخوره."

از کامند های زیر استفاده شده. 

```
for create .keystore
keytool -genkeypair -v -storetype PKCS12 -keystore xxx.keystore -alias KEY_ALIAS -keyalg RSA -keysize 2048 -validity 10000

for create .jks
keytool -genkey -v -keystore key.jks -storetype JKS -keyalg RSA -keysize 2048 -validity 10000 -alias KEY_ALIAS

sudo java -jar bundlesigner-0.1.6.jar genbin  --bundle app.aab --bin /Users/mac10/Desktop --v2-signing-enabled true --v3-signing-enabled false --ks key.jks
```
رمز و اطلاعات هم درست وارد میشه. 

پروژه های کراس پلتفرم ری اکت تو اندروید یه 
index.android.bundle
داره که کل  جی اس تو اون هست . آیا این رو هم در بین نهایی گنجانده میشه ؟

**Comment by club9822** [comment]
برای کی استفاده کردم که هر دو ۳ مگ بین خروجی دادن .jks   و هم از .keystore هم از فایل

**Comment by mahboobehad** [comment]
سلام 
برای خطای شناسایی بسته لطفا مطمئن بشید همون باندلی رو به برنامه‌ی باندل‌ساینر می‌دید که در پیشخان آپلود کردید، هر تغییری در سورس یا ریسورس‌های برنامه باعث می‌شه که بسته‌های شما وریفای نشه.
فایل بین برای تولید ساین استفاده می‌شه و فقط شامل دایجست بسته‌های برنامه هست به همین دلیل حجم کمتری‌ در مقایسه با باندل داره.

**Comment by club9822** [comment]
برای اولین بار در تعریف اپ جدید از ورژن  ای ای بی ۳۳ مگ استفاده شده بود که با همین کی استور میام و دوباره میخوام بین فایل بساازم. تو اون نسخه از کی استور از کامند زیر 

`keytool -genkey -v -keystore my-release-key.keystore -alias my-key-alias -keyalg RSA -keysize 2048 -validity 10000

`
 . برای جنریت فایل کی استفاده کردیم که یه فایل حدود ۲ کیلو بایتی میده
  


برای ساخت فایل بین از کامند 

`sudo java -jar bundlesigner-0.1.6.jar genbin -v --bundle app-release.aab --bin /Users/airtour7/Desktop --v2-signing-enabled true --v3-signing-enabled false --ks my-release-key.keystore -v`
استفاده میکنم و همون کی قدیمی رو به عنوان کی بهش میدم. خروجی ۳  بدون ارور 
مگ میده . باز تو داشبورد خطای 
`مشکلی در شناسایی بسته‌ها پیش‌ آمده است، لطفا فایل باینری را دوباره تولید و بارگذاری کنید.`
میده
. تو مرحله پردازش فایل حدود ۱۵ ثانیه میره تا به این ارور برسه .فک کنم مرحله ساین و کی رو رد میکنه وگرنه همون اول باید خطا میداد
ای کاش اونجا یه لاگر داشت یا حداقل لاگ پروسس در کامند لاین چاپ میشد

**Comment by club9822** [comment]
تبدیل ۳۳مگ به ۳.۲ رو نمیتونم درک کنم

**Comment by mahboobehad** [comment]
بله درسته این خطا مربوط به شناسایی بسته‌های برنامه هست. این مشکل معمولا در حالتی پیش میاد که بعد از آپلود باندل در پیشخان بازار، فایل باندل رو تغییر داده باشید. فرآیند ساین کردن برنامه در مرحله‌ی ابتدایی دایجست بسته‌ها رو حساب می‌کنه، در مرحله‌ی شناسایی بسته ما چک می‌کنیم که آیا محتوای ساین شده با محتوای بسته‌های باندلی که آپلود کردید سازگاری داره یا نه. بنابراین اگر باندلی که آپلود کردید با باندلی که برای تولید  فایل امضا استفاده می‌کنید تفاوت داشته باشه (هر چند جزیی) این خطا پیش میاد.
اگر با این چک باز هم مشکل حل نشد لطفا با پشتیابی بازار در ارتباط باشید تا بتونیم دقیق‌تر بررسی کنیم

**Comment by club9822** [comment]
ممنونم . فک میکنم از این باشه. چک میکنم و بعد همینجا اعلام میکنم.ای کاش در پلن جای بود که نسخه اول آپلودی رو بشه دانلود کرد

**Comment by mahboobehad** [comment]
خواهش می‌کنم. پیشنهادتون رو بررسی می‌کنیم.

**Comment by club9822** [comment]
ممنونم. مجبور شدم دوباره با باندل نیم جدید اپ پابلیش کنم . چون فایل  ای ای بی اول نبود.
دقیقا مشکل از همین بود. 
ممنون.
