### ISSUE TITLE
Unclear exception messages

### ISSUE THREAD

**Issue by matinzd** [cafebazaar/bundle-signer#17]
I think it's better to make this message more clear. If the bin folder or path does not exist this exception will occur.

```
Input bundle file does not exist
```

Suggestion: 

```
Output bin path does not exist
```

https://github.com/cafebazaar/bundle-signer/blob/5f0883c5b519874a89fb94ff5d9e24d23c0ea061/src/main/java/ir/cafebazaar/bundlesigner/BundleSignerTool.java#L313

To make things easier you can create the path based on the passed parameter.

**Comment by mahboobehad** [comment]
Thanks for the report. The next release will fix this issue.

**Comment by imanpr** [comment]
Missing output Bin file path
