### ISSUE TITLE
`Input bundle file does not exist` with `bundlesigner-0.1.6.jar`

### ISSUE THREAD

**Issue by mhkarami** [cafebazaar/bundle-signer#19]
Hi. i can not create bin file. result of the command is : `Input bundle file does not exist`
my command :
`java -jar bundlesigner-0.1.6.jar genbin  -v --bundle app-release.aab --bin /home/bin_files/  --v2-signing-enabled true --v3-signing-enabled false --ks MyKeyStore.jks --ks-pass pass:XXXXXXXX`
the result of command `java -XX:+PrintCommandLineFlags -version` :
```
java -XX:+PrintCommandLineFlags -version
-XX:G1ConcRefinementThreads=4 -XX:InitialHeapSize=196997952 -XX:MaxHeapSize=3151967232 -XX:+PrintCommandLineFlags -XX:ReservedCodeCacheSize=251658240 -XX:+SegmentedCodeCache -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:+UseG1GC -XX:-UseLargePagesIndividualAllocation
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
```
I put the files `bundlesigner-0.1.6.jar` and `app-release.aab` and `MyKeyStore.jks` in a folder and created directories` /home` and `/home/bin_files` and `/bin_files` in that folder.

this error does not shown when i use `bundlesigner-0.1.4.jar`,but bin file also not generate

**Comment by mahboobehad** [comment]
Hello
Please point to a directory that exists on your computer; Consider that / is the name of the root directory in UNIX-based operating systems. Simply replace /home/bin_file with any other valid path including dot which saves bin file in the current directory.
