### ISSUE TITLE
تولید فایل خروجی برای کلید keystore

### ISSUE THREAD

**Issue by alikalantaripor** [cafebazaar/bundle-signer#21]
<div dir=rtl>
سلام 

خروجی فایل امضا شده من از نوع `.keystore` هست.و طبق توضیحات لینک زیر ساخته شده است:

https://reactnative.dev/docs/signed-apk-android

فلگ های مربوط به باندل شمارا چطور باید تنظیم کنم؟

منظور از `PKCS12` استفاده شده.

</div>
`keytool -genkeypair -v -storetype PKCS12 -keystore my-upload-key.keystore -alias my-key-alias -keyalg RSA -keysize 2048 -validity 10000`

**Comment by mahboobehad** [comment]
<div dir="rtl">
سلام 
می‌تونید از فلگ‌های java key store استفاده کنید.
</div>
