### ISSUE TITLE
Error while loading private key and certificates from the keystore.

### ISSUE THREAD

**Issue by hojjat-reyhane** [cafebazaar/bundle-signer#27]
سلام و وقت بخیر
موقع استفاده از bundle-signer با jks با این خطا روبرو میشیم.
لازم به ذکر هست که این کلید برای نسخه‌های قبلی برنامه توی بازار استفاده شده و امکان استفاده از کلید دیگه‌ای رو نداریم.

Error while loading private key and certificates from the keystore.
[com.android.tools.build.bundletool.model.exceptions.CommandExecutionException$$Lambda$16/2083562754.create(Unknown Source), com.android.tools.build.bundletool.model.exceptions.InternalExceptionBuilder.build(InternalExceptionBuilder.java:57), com.android.tools.build.bundletool.model.SignerConfig.extractFromKeystore(SignerConfig.java:160), com.android.tools.build.bundletool.commands.BuildApksCommand.populateSigningConfigurationFromFlags(BuildApksCommand.java:1059), com.android.tools.build.bundletool.commands.BuildApksCommand.fromFlags(BuildApksCommand.java:593), com.android.tools.build.bundletool.commands.BuildApksCommand.fromFlags(BuildApksCommand.java:559), ir.cafebazaar.bundlesigner.BundleToolWrapper.buildApkSet(BundleToolWrapper.java:70), ir.cafebazaar.bundlesigner.command.GenBinCommand.execute(GenBinCommand.java:119), ir.cafebazaar.bundlesigner.BundleSignerTool.getContentDigest(BundleSignerTool.java:372), ir.cafebazaar.bundlesigner.BundleSignerTool.main(BundleSignerTool.java:126)]

خیلی ممنون میشم راهنمایی بفرمایید.

**Comment by mahboobehad** [comment]
سلام وقتتون بخیر
می‌شه کامندی که می‌زنید رو بفرستید؟

**Comment by hojjat-reyhane** [comment]
بله
java -jar bundlesigner-0.1.9.jar genbin  -v  --bundle app.aab --bin . --v2-signing-enabled true --v3-signing-enabled false --ks key.jks --ks-key-alias **** --key-pass pass:****

**Comment by mahboobehad** [comment]
به نظر می‌رسه مشکل از کلید شما نیست و در مرحله‌ی پردازش باندل این خطا رخ داده.
در مسیر تمپ سیستم‌عامل شما باید فایلی با نام 
bundlesigner.log
ایجاد شده باشه (بعد از هر بار اجرای کامند با باندل ساینر لاگ‌هایی برای دیباگ در این فایل نوشته می‌شه) . خیلی ممنون می‌شم اگر از طریق پشتیبانی بازار این فایل رو برای ما بفرستید. اگر لطف کنید خروجی کامند 
java -version
و نام سیستم عامل رو هم بفرستید.

**Comment by hojjat-reyhane** [comment]
خیلی متشکرم
توی فایل لاگ فقط این لاگ‌ها با هر بار اجرا نوشته میشه
2022-02-08 11:03:18 INFO  BundleSignerTool:74 - Set up project, java version: 1.8.0_25, vendor: Oracle Corporation, vm: Java HotSpot(TM) 64-Bit Server VM, jre: Java(TM) SE Runtime Environment, f-memory: 246372192, m-memory: 3717201920
2022-02-08 11:03:21 INFO  GenBinCommand:118 - started genbin command.
2022-02-08 11:03:21 INFO  BundleToolWrapper:27 - loaded keystore.
2022-02-08 11:03:21 INFO  BundleSignerTool:93 - Process finished.

این هم ورژن جاوا
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b18)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

سیستم عامل ویندوز ۱۰

**Comment by mahboobehad** [comment]
می‌شه لطفا با یک کلید متفاوت در ویندوز تست کنید و همچنین اگه ممکنه در سیستم‌عامل دیگه‌ای از خانواده‌ی لینوکس با کلید اصلی خودتون، کامند تولید فایل رو اجرا کنید؟

**Comment by hojjat-reyhane** [comment]
با آپدیت کردن جاوا تونستیم فایل رو تولید کنیم. به نظر مشکل از نسخه جاوا بوده!
خیلی متشکرم از پاسخ‌گویی و وقتی که گذاشتین

**Comment by Alireza-Jamali** [comment]
در توضیحات ذکر شده "You need to install Java 8 or above to run this program" ولی با جاوا 8 همیشه همین ارور دریافت میشه و باید با جاوا 11 اجرا بشه تا کار کنه، پیشنهاد میدم اصلاح کنید تا بقیه زمانشون هدر نره...
