### ISSUE TITLE
error: failed to deserialize resources.pb: unknown type 'macro'

### ISSUE THREAD

**Issue by Majidahmadi** [cafebazaar/bundle-signer#29]
این خطا بعد از بروزرسانی های مکرر روی پروژه برای ساین فایل aab صادر میشود. لطفا راهنمایی بفرمایید.

```
C:\Users\mypc\AppData\Local\Temp\3859703532227306912\proto.apk: error: failed to deserialize resources.pb: unknown type 'macro'.
C:\Users\mypc\AppData\Local\Temp\3859703532227306912\proto.apk: error: failed to load APK.
Command '[C:\Users\mypc\AppData\Local\Temp\AutoValue_BuildApksCommand8906874086694050195\output\windows\aapt2.exe, convert, --output-format, binary, -o, C:\Users\mypc\AppData\Local\Temp\3859703532227306912\binary.apk, C:\Users\mypc\AppData\Local\Temp\3859703532227306912\proto.apk]' didn't terminate successfully (exit code: 1). Check the logs.
[com.android.tools.build.bundletool.model.exceptions.InternalExceptionBuilder.build(InternalExceptionBuilder.java:57), com.android.tools.build.bundletool.model.DefaultCommandExecutor.executeImpl(DefaultCommandExecutor.java:57), com.android.tools.build.bundletool.model.DefaultCommandExecutor.execute(DefaultCommandExecutor.java:33), com.android.tools.build.bundletool.model.Aapt2Command$1.convertApkProtoToBinary(Aapt2Command.java:41), com.android.tools.build.bundletool.io.ApkzlibApkSerializerHelper.writeToZipFile(ApkzlibApkSerializerHelper.java:122), com.android.tools.build.bundletool.io.ApkzlibApkSerializerHelper.writeToZipFile(ApkzlibApkSerializerHelper.java:101), com.android.tools.build.bundletool.io.SplitApkSerializer.writeToDisk(SplitApkSerializer.java:68), com.android.tools.build.bundletool.io.SplitApkSerializer.writeSplitToDisk(SplitApkSerializer.java:42), com.android.tools.build.bundletool.io.ApkSetBuilderFactory$ApkSetArchiveBuilder.addSplitApk(ApkSetBuilderFactory.java:106), com.android.tools.build.bundletool.io.ApkSerializerManager$ApkSerializer.serialize(ApkSerializerManager.java:461), com.android.tools.build.bundletool.io.ApkSerializerManager.lambda$null$3(ApkSerializerManager.java:225), com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125), com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57), com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78), java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136), java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base/java.lang.Thread.run(Thread.java:833)]
```

**Comment by maze1377** [comment]
با سلام
برای تولید apk از فایل aab شما از ابزار bundle tool گوگل استفاده میکنیم.
خطایی که دریافت کردید از این لایه raise شده
به نظر میرسه نوع macro که استفاده کردید شناخته شده نیست
لطفا سمت کد خودتون را دقیق تر بررسی کنید:
https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/tools/aapt2/format/proto/ProtoDeserialize.cpp#435

**Comment by maze1377** [comment]
سلام مجید جان این تعریف macro هست که گوگل ارایه میده:
In computer programming, a macro is a rule or pattern that specifies how a certain input should be mapped to a replacement output. Applying a macro to an input is known as macro expansion. The input and output may be a sequence of **lexical tokens** or **characters**, or a **syntax tree**.

یعنی قرار نیست فایلی داشته باشی که پسوندش macro باشه در واقع زمانی که داره syntax tree ات را برای تحلیل کردن میسازه یک موردی تعریف شده اونجا که شناخته شده نیست برای aapt گوگل و نمیتونه تشخیصش بده.

میتونی این مورد را با bundle tool خود گوگل پلی هم تست کنی.

**Comment by maze1377** [comment]
اگر با bundle tool خودتون درست داره این مورد کار میکنه لطف کن نسخه اش را به ما بگو تا بتونیم دقیق تر این مورد را بررسی کنیم.

**Comment by RezaDizaji** [comment]
سلام خدمت دوستان و همکاران. متاسفانه بنده هم به این مشکل خوردم با bundlesigner بازار، ورژن‌های مختلف هم امتحان کردم از همین آخری که ۰.۱.۱۰ باشه تا ۰.۱.۲.
ولی جواب نداد. رفتم پیشنهاد @maze1377 رو اجرا کردم و با bundletool گوگل ورژن ۱.۱۱.۰ و دستوری که پایین میذارم یه فایل apks درست کردم و مشکلی نداشتم. 

`java -jar bundletool-all-1.11.0.jar build-apks --bundle=bazaar/release/app-bazaar-release.aab --output=output/my_app.apks`

امیدوارم کمکی کرده باشم و همت کنید این مشکل زودتر حل بشه تا بازم آپدیتا رو بی دردسر منتشر کنیم. 🤦🏻‍♂️

**Comment by mahboobehad** [comment]
سلام 
ممنونم برای وقتی که گذاشتید.
نسخه‌ی bundletool استفاده شده در پروژه‌ی bundle signer قدیمی‌تر از نسخه‌ای هستید که برای تولید باندل استفاده کردید. ما بروزرسانی bundle signer رو بررسی می‌کنیم. در این بازه اگر ممکنه فایل باندل رو با نسخه 1.4.0 از bundletool تولید کنید.

**Comment by RezaDizaji** [comment]
> سلام ممنونم برای وقتی که گذاشتید. نسخه‌ی bundletool استفاده شده در پروژه‌ی bundle signer قدیمی‌تر از نسخه‌ای هستید که برای تولید باندل استفاده کردید. ما بروزرسانی bundle signer رو بررسی می‌کنیم. در این بازه اگر ممکنه فایل باندل رو با نسخه 1.4.0 از bundletool تولید کنید.

خواهش می‌کنم لطف دارید. بنده کاری که گفتید انجام دادم و همون ارور رو گرفتم با نسخه‌ی ۱.۴.۰ bundletool. اگه bundletool رو آپدیت کنید تو پکیج مشکل حل میشه.
ممنون از شما.

اینم ارور bundletool:
`/var/folders/7b/32dqrtq5775660lrb2c06cm40000gn/T/13059121098207816770/proto.apk: error: failed to deserialize resources.pb: unknown type 'macro'.
/var/folders/7b/32dqrtq5775660lrb2c06cm40000gn/T/13059121098207816770/proto.apk: error: failed to load APK.
[BT:1.4.0] Error: Command '[/var/folders/7b/32dqrtq5775660lrb2c06cm40000gn/T/AutoValue_BuildApksCommand5313920202184340379/output/macos/aapt2, convert, --output-format, binary, -o, /var/folders/7b/32dqrtq5775660lrb2c06cm40000gn/T/13059121098207816770/binary.apk, /var/folders/7b/32dqrtq5775660lrb2c06cm40000gn/T/13059121098207816770/proto.apk]' didn't terminate successfully (exit code: 1). Check the logs.
com.android.tools.build.bundletool.model.exceptions.CommandExecutionException: Command '[/var/folders/7b/32dqrtq5775660lrb2c06cm40000gn/T/AutoValue_BuildApksCommand5313920202184340379/output/macos/aapt2, convert, --output-format, binary, -o, /var/folders/7b/32dqrtq5775660lrb2c06cm40000gn/T/13059121098207816770/binary.apk, /var/folders/7b/32dqrtq5775660lrb2c06cm40000gn/T/13059121098207816770/proto.apk]' didn't terminate successfully (exit code: 1). Check the logs.
	at com.android.tools.build.bundletool.model.exceptions.InternalExceptionBuilder.build(InternalExceptionBuilder.java:57)
	at com.android.tools.build.bundletool.model.DefaultCommandExecutor.executeImpl(DefaultCommandExecutor.java:57)
	at com.android.tools.build.bundletool.model.DefaultCommandExecutor.execute(DefaultCommandExecutor.java:33)
	at com.android.tools.build.bundletool.model.Aapt2Command$1.convertApkProtoToBinary(Aapt2Command.java:41)
	at com.android.tools.build.bundletool.io.ApkzlibApkSerializerHelper.writeToZipFile(ApkzlibApkSerializerHelper.java:122)
	at com.android.tools.build.bundletool.io.ApkzlibApkSerializerHelper.writeToZipFile(ApkzlibApkSerializerHelper.java:101)
	at com.android.tools.build.bundletool.io.SplitApkSerializer.writeToDisk(SplitApkSerializer.java:68)
	at com.android.tools.build.bundletool.io.SplitApkSerializer.writeSplitToDisk(SplitApkSerializer.java:42)
	at com.android.tools.build.bundletool.io.ApkSetBuilderFactory$ApkSetArchiveBuilder.addSplitApk(ApkSetBuilderFactory.java:106)
	at com.android.tools.build.bundletool.io.ApkSerializerManager$ApkSerializer.serialize(ApkSerializerManager.java:461)
	at com.android.tools.build.bundletool.io.ApkSerializerManager.lambda$null$3(ApkSerializerManager.java:225)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:117)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:38)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)`

**Comment by maze1377** [comment]
در ورژن ۱.۱۱ این مشکل حل شده
دوباره تلاش کنید.

**Comment by mahboobehad** [comment]
لطفا از طریق پشتیبانی بازار فایل برنامه رو بفرستید تا بتونیم بررسی کنیم.

**Comment by Majidahmadi** [comment]
@mahboobehad 

آیا برای رفع این مشکل اقدام جدیدی انجام شده است؟ ما برای کاهش حجم بسته های تولید شده بسیار به این قابلیت شدیدا نیاز داریم .

**Comment by maze1377** [comment]
این مشکل یک حالت خاصی هست که در حال بررسی آن هستیم.

زمانی که با اخرین ورژن اندروید استدیو خروجی میگیریم و خودمون تست میکنیم مشکلی وجود ندارد.

**Comment by Majidahmadi** [comment]
@maze1377 
بسار عالی ، اگر اطلاعاتی از پروژه ما نیاز دارید که به روند رفع مشکل کمک میکنه بفرمایید تا اطلاع بدم.

**Comment by maze1377** [comment]
فایل aab که ارسال کرده بودید با اخرین ورژن bundle signer داره درست کار میکنه.

**Comment by mahboobehad** [comment]
دوستان ممکنه با نسخه‌ی 0.1.12 فایل رو تولید کنید؟

**Comment by Majidahmadi** [comment]
با تشکر فراوان ، بله **کاملا مشکل رفع شده** و فایل bin به درستی ایجاد شد . موفق باشید.
