### ISSUE TITLE
java.io.IOException: Failed to read Keystore password for signer

### ISSUE THREAD

**Issue by Hamed1984** [cafebazaar/bundle-signer#4]
سلام
این تابع را برای اجرای پلاگین شما در یونیتی نوشتم و متاسفانه نمی توانم پسورد را داخل آرگومان ها قرار دهم

private async void Sign(string bundleFile, string keyFile, string password)
        {
                string jarFile = "bundlesigner-0.1.3.jar";
            string outDir = "/home/bin_files/";

                string arguments = string.Format("-jar \"{0}\" genbin  -v --bundle \"{1}\" --bin {2}  --v2-signing-enabled true --v3-signing-enabled false --ks \"{3}\" pass:{4}",
                   jarFile, bundleFile, outDir, keyFile, password);

                ProcessStartInfo ProcessInfo = new ProcessStartInfo()
                {
                    UseShellExecute = false,
                    CreateNoWindow = true,
                    FileName = "java.exe",
                    Arguments = arguments,
                    RedirectStandardError = true,
                    RedirectStandardOutput = true
                };

                Process process = Process.Start(ProcessInfo);
                process.EnableRaisingEvents = false;
                await WaitForExitAsync(process);

                String output = process.StandardOutput.ReadToEnd();
                String error = process.StandardError.ReadToEnd();
            
                UnityEngine.Debug.Log(string.Format("{0}\n{1}\n{2}", arguments, output, error)); 
        }
اشکال کار من کجاست؟

**Comment by mahboobehad** [comment]
سلام!
برای ورودی دادن پسورد می‌تونید به شکل زیر جلو برید
--ks-pass  pass:your_password
تو کدی که نوشتید فلگ ست نشده

**Comment by Hamed1984** [comment]
سلام
اون مشکل حل شد الان این ارور و میده
Invalid dex file indices, expecting file 'classes?.dex' but found 'classes2.dex'.

**Comment by mahboobehad** [comment]
این خطا از سمت برنامه‌ی 
bundletool 
اومده، به نظر می‌رسه کانفیگ پروژه‌ی باندلی که ورودی دادید نیاز به تغییر داره.

**Comment by Hamed1984** [comment]
خروجی باندل توسط یونیتی هستش
چه تغییری می تونم روش انجام بدم؟

**Comment by mahboobehad** [comment]
لطفا خطایی که گرفتید رو سرچ کنید یه سری مشکل مشابه قبلا برای باندل تول مطرح شده.

**Comment by Hamed1984** [comment]
سرچ می کنم چیزی پیدا نمی کنم دقیقاً کجا رو باید بگردم؟
باندل تول کجا هست؟

**Comment by mahboobehad** [comment]
فکر می‌کنم [این لینک](https://forum.unity.com/threads/cant-build-with-multidex-enabled.773348/) به خطای شما نزدیک باشه. 
در مورد باندل تول هم که پرسیدید، ابزار گوگل برای پردازش برنامه‌های باندل هست.
