### ISSUE TITLE
java.util.zip.ZipException when generate a bin file

### ISSUE THREAD

**Issue by BasetEsmaeili** [cafebazaar/bundle-signer#45]
Hello 👋🏻.
**Describe the bug**
I receive this error when I run the command to generate a bin file
> java.util.zip.ZipException: ZipFile invalid LOC header (bad signature)
[ir.cafebazaar.bundlesigner.BundleToolWrapper.buildApkSet(BundleToolWrapper.java:72), ir.cafebazaar.bundlesigner.command.GenBinCommand.execute(GenBinCommand.java:119), ir.cafebazaar.bundlesigner.BundleSignerTool.getContentDigest(BundleSignerTool.java:377), ir.cafebazaar.bundlesigner.BundleSignerTool.main(BundleSignerTool.java:126)]

**To Reproduce**
I use this command: 
> java -jar bundlesigner-0.1.13.jar genbin  -v --bundle file.aab --bin .  --v2-signing-enabled true --v3-signing-enabled false --ks /Users/user/key
**Screenshots**
<img width="1318" alt="Screenshot 1401-12-20 at 21 13 29" src="https://user-images.githubusercontent.com/30471156/224504176-01b76cd4-161b-439d-b5c2-5ca69dfbef81.png">

**Versions**
- Version of the library that we are using: [eg: 0.1.13]

**Comment by mahboobehad** [comment]
Thanks for the report. There's a bug, and we are working on it.

**Comment by maze1377** [comment]
What is the version of your bundle tool? Please sign your application using an older version such as 0.1.12, and report any issues encountered. Thank you.

**Comment by BasetEsmaeili** [comment]
We use 0.1.13, but I tested with 0.1.12 and got the same error.

<img width="1328" alt="Screenshot 1401-12-21 at 11 28 52" src="https://user-images.githubusercontent.com/30471156/224532089-030c8881-5f33-4512-8313-9add68b895c9.png">

**Comment by maze1377** [comment]
I need more additional information regarding your environment. Specifically, could you please provide details on your operating system version and the Java version currently installed?

**Comment by maze1377** [comment]
Could you please test the bundle-signer command with the new version using this link: https://github.com/cafebazaar/bundle-signer/suites/11506203099/artifacts/594744356

I would really appreciate your help in testing this version. Thank you so much for your time and attention.

**Comment by BasetEsmaeili** [comment]
I tested the new version, but I still get the same error.
I use an M1 Mackbook pro with macOS Ventura 13.2.1, and my JDK version is corretto-17.0.6

**Comment by BasetEsmaeili** [comment]
Hello 👋🏻.
I figured out the scenario when I used the [bundle signer](https://github.com/cafebazaar/bundle-signer) for a standard aab file; everything was fine, and tools generated the bin file; but when I downloaded the abb file that I uploaded to the CafeBazaar panel, the tools showed this error.

**Comment by maze1377** [comment]
Greetings,

We have successfully tested the sign application using the M2 Pro laptop and JDK version 19.0.1. All functions were found to be working seamlessly.
We kindly request that you submit your application for support.
Thank you.

**Comment by BasetEsmaeili** [comment]
Greetings,
I apologise for the delayed response.
I found the issue and when I changed my JDK to Zulu JDK the issue is gone.

**Comment by BasetEsmaeili** [comment]
So I close the issue.

**Comment by maze1377** [comment]
Hello,
Thank you for letting us know about the solution to the issue you were facing. We appreciate your prompt action in resolving the problem.
Thank you for your contribution.
Best regards.
