### ISSUE TITLE
مشکل در ساین هنگام اجرای کامند At least one signer must be specified

### ISSUE THREAD

**Issue by Banouie** [cafebazaar/bundle-signer#52]
At least one signer must be specified
[ir.cafebazaar.bundlesigner.BundleSignerTool.getContentDigest(BundleSignerTool.java:337), ir.cafebazaar.bundlesigner.BundleSignerTool.main(BundleSignerTool.java:126)]
zsh: command not found: --v2-signing-enabled
zsh: command not found: --key

خطای بالا را هنگام ساین کردن داریم

**Comment by mahboobehad** [comment]
Thanks for the report. Would you please provide the command you've entered? It seems that the command is broken by multiline char.
