### ISSUE TITLE
No bin file is generated using version 0.1.4

### ISSUE THREAD

**Issue by sm-hoseini** [cafebazaar/bundle-signer#6]
با سلام 
با توجه راهنمای موجود در مستندات این نرم افزار من با  استفاده از نسخه
0.1.3
 میتونم فایل بین را با موفقیت  تولید کنم ولی در صورت استفاده از نسخه 
 0.1.4 
  هیچ فایلی ساخته نمیشود 
  تنها تغییر در ارگمان های ورودی تغییر در اسم فایل 
  jar هست
  پ. ن: در هر دو روش پس از اتمام کار پیام
  Faild to remove tmp dir 
  دریافت میشود

**Comment by srmarjani** [comment]
سیستم عاملی که استفاده می کنید رو لطفا بگین

**Comment by sm-hoseini** [comment]
> 
> 
> سیستم عاملی که استفاده می کنید رو لطفا بگین

Windows 10

**Comment by srmarjani** [comment]
اگه به سیستم عامل لینوکس دسترسی دارین لطفا برای تولید  فایل بین ازش استفاده کنید.
ممنون
ابزار در محیط ویندوز مشکلاتی داره که داریم روش کار می کنیم

**Comment by sm-hoseini** [comment]
این مشکل با سیستم عامل اوبونتو 18 هم وجود داره
با نسخه 0.1.3 میتونم فایل بین رو تولید کنم درنهایت پیام 
Digest content generated
نمایش داده میشه ولی با نسخه 0.1.4 هیچ پیامی نمایش داده نمیشه و هیچ فایلی هم ساخته نمیشه

**Comment by mahboobehad** [comment]
سلام 
تغییرات نسخه‌ی ۴ به گونه‌ای بوده که نیاز به مموری بیشتری برای پردازش باندل داریم. در حال بهینه‌سازی باندل‌ساینر هستیم .

**Comment by sm-hoseini** [comment]
من نزدیک 10 گیگ به 6 گیگ فضای آزاد رمم اضافه کردم و تونستم  ساین رو روی سیتم عامل اوبونتو با موفقیت انجام بدم. ناگفته نماند که سایز باندل من 290 مگابایت بود.  اگه این سایز دو برابر میشد فکر کنم  عملا از نظر سخت افزار دیگه هیچ وقت نمیتونستم فایلم رو ساین کنم.
ممنون از پیگیریتون . منتظر نسخه جدید هستم

**Comment by AlirezaHadjar** [comment]
با macos هم مشکل داره

**Comment by mahboobehad** [comment]
سلام لطفا یک ایشوی جدید باز کنید
